name : Docker-CI
trigger:
  branches:
    include:
      - main
 
pool:
  vmImage: 'ubuntu-latest'

variables:
  ImageName: 'deezer-downloader:latest'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: DockerImage
    displayName: Build and push Docker image
    steps:
    - task: Docker@2
      displayName: 'Build the Docker image'
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'dejan995/deezer-downloader'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        buildContext: '.'
        tags: 'latest'
    - task: Docker@2
      displayName: 'Push the Docker image to Dockerhub'
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'dejan995/deezer-downloader'
        command: 'push'
        tags: 'latest'
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest')) 